// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBWyhpXZNZi1G6iVQ2VP-9zuhuctrIBs0',
    appId: '1:601888460370:web:88990c3fb2071c8fd7598b',
    messagingSenderId: '601888460370',
    projectId: 'fir-1-2730f',
    authDomain: 'fir-1-2730f.firebaseapp.com',
    storageBucket: 'fir-1-2730f.appspot.com',
    measurementId: 'G-FZ3JDVSYBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbsBc_Ym513WDeNzF-GsdN_U2iCkMZEIw',
    appId: '1:601888460370:android:11d9e42835fff906d7598b',
    messagingSenderId: '601888460370',
    projectId: 'fir-1-2730f',
    storageBucket: 'fir-1-2730f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaz_HAh3hiKSDH4L9QwfmvLqWLVtb4_nM',
    appId: '1:601888460370:ios:0505203695da7adbd7598b',
    messagingSenderId: '601888460370',
    projectId: 'fir-1-2730f',
    storageBucket: 'fir-1-2730f.appspot.com',
    iosClientId: '601888460370-31kvc0h5o2glusqfgt7oqtbglbs2rp02.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireb1',
  );
}
